server:
  port: 8761
  compression:
    enabled: true

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000

spring:
  application:
    name: eureka-server
  profiles:
    active: default

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN